/* PRISM-X — shells.js · PHASE 3: OUTER SHELLS
 * Faceless AI content brands. Each Shell researches its niche, generates a
 * daily content drop per platform (X / TikTok / YT Shorts / IG Reels), wires
 * one CTA per post to its offer source, and evolves on engagement:
 * >10% weekly growth ⇒ scale volume · stagnant ⇒ 7-day persona swap test.
 *
 * Honesty note: trend scans, views, likes and follower growth are a labeled
 * simulation on the shared market sim clock (a serverless app can't scrape
 * platforms or read analytics APIs). The CONTENT is real — scripts, threads,
 * carousels and meme concepts ready to publish, generated by the Local Cortex
 * (bulk daily drops) or live Claude via the Neural Link (Shell Builder AI and
 * on-demand drops). Auto-Upload queues real X posts into the Broadcast Queue;
 * other platforms wait on future API integrations, exactly as the spec allows.
 */
window.PRISM = window.PRISM || {};

PRISM.shells = (function () {
  "use strict";
  const D = () => PRISM.data, E = () => PRISM.engine, S = () => PRISM.store, U = () => PRISM.ui, G = () => PRISM.ghosts;
  const DAY = 86400000;
  const MAX_POSTS_ARCHIVE = 40;

  function now() { return Date.now() + (S().state.ghostSimOffset || 0); } /* shared sim clock */
  const pick = (r, arr) => arr[Math.floor(r() * arr.length)];
  const money = n => "$" + Math.round(n).toLocaleString();

  /* ------------------------------------------------------------------ *
   * Catalogs
   * ------------------------------------------------------------------ */
  const PLATFORMS = ["X", "TikTok", "YT Shorts", "IG Reels"];

  const NICHES = {
    "Fitness Motivation":                  { heat: 0.80, topics: ["discipline over motivation", "training when nobody claps", "the 5am body vs the 5am mind", "progressive overload for life", "rest as a weapon"] },
    "Money Hacks":                         { heat: 0.85, topics: ["boring income stacks", "the $0 → $100 ladder", "skills that print", "expenses nobody audits", "cashflow before status"] },
    "Crypto Signals":                      { heat: 0.90, topics: ["narrative rotation", "reading unlock calendars", "position sizing psychology", "surviving chop", "the exit plan nobody writes"] },
    "High-Performance Mindset":            { heat: 0.75, topics: ["identity before habits", "the boredom threshold", "single-tasking as edge", "ruthless calendars", "recovery loops"] },
    "Faceless Copywriting / Marketing Tips": { heat: 0.70, topics: ["hooks that stop thumbs", "one-line CTAs", "proof stacking", "the anti-guru angle", "offers people screenshot"] },
    "AI Tools / Tech":                     { heat: 0.95, topics: ["one AI workflow a day", "tools that replace teams", "prompt patterns that ship", "automation before delegation", "the 10-minute build"] }
  };
  const DEFAULT_NICHE_META = { heat: 0.75, topics: ["the unfair basics", "systems over vibes", "what winners automate", "proof beats promises", "the 80/20 nobody does"] };
  function nicheMeta(niche) { return NICHES[niche] || DEFAULT_NICHE_META; }

  const PERSONAS = {
    "Alpha Mentor": {
      desc: "Commands, discipline framing, zero excuses. Short declaratives.",
      fit: { "Fitness Motivation": 1.0, "High-Performance Mindset": 1.0, "Money Hacks": 0.9 },
      hooks: ["Hard truth:", "Nobody is coming to save you.", "Read this before you quit:", "Discipline check:", "You don't need more time. You need a standard."],
      signoffs: ["Now execute.", "Standards, not moods.", "Zero excuses tomorrow.", "We go again."]
    },
    "Calm Genius": {
      desc: "Quiet certainty, elegant observations, no hype.",
      fit: { "AI Tools / Tech": 1.0, "High-Performance Mindset": 0.95, "Faceless Copywriting / Marketing Tips": 0.9 },
      hooks: ["Quiet observation:", "Most people miss this:", "A pattern worth noticing:", "The simplest edge nobody uses:", "Filed under: obvious in hindsight."],
      signoffs: ["That's the whole trick.", "Simple. Not easy.", "Noted and applied.", "Carry on."]
    },
    "Savage Meme Lord": {
      desc: "Meme-native chaos with a sharp point underneath. 💀 energy.",
      fit: { "Money Hacks": 1.0, "Crypto Signals": 0.95, "Fitness Motivation": 0.85 },
      hooks: ["POV:", "nobody: — me at 3am:", "this you? 💀", "breaking: local genius discovers", "not the algorithm blessing this again 😭"],
      signoffs: ["screenshot it, cowards.", "you saw it here first 💀", "ok back to the lab.", "ratio the doubters."]
    },
    "Tactical Copywriter": {
      desc: "Frameworks, swipe files, numbers. Every post is a mini-lesson.",
      fit: { "Faceless Copywriting / Marketing Tips": 1.0, "Money Hacks": 0.9, "AI Tools / Tech": 0.85 },
      hooks: ["Steal this framework:", "One line doubled my CTR:", "Swipe file, entry #47:", "The 3-part hook that never misses:", "Copy lesson in 15 seconds:"],
      signoffs: ["Swipe responsibly.", "Test it today.", "The file grows.", "Your CTR will thank you."]
    },
    "Mysterious Oracle": {
      desc: "Cryptic foresight, pattern talk, few words. Never explains twice.",
      fit: { "Crypto Signals": 1.0, "AI Tools / Tech": 0.9, "High-Performance Mindset": 0.85 },
      hooks: ["The pattern repeats.", "Few will understand what happens next.", "Watch what they ignore.", "It has already begun.", "The signal hides in the noise."],
      signoffs: ["You were warned kindly.", "The cycle continues.", "Few.", "Remember this post."]
    }
  };

  const OFFER_SOURCES = ["Promote Product Ghosts", "Promote Affiliate Links", "Collect Emails for List", "Drive Traffic to Lead Gen Clone"];

  const TRENDS = [
    { angle: "before/after transformation cuts", sound: "sped-up ambient phonk", src: "TikTok sounds chart" },
    { angle: "'things I stopped doing' listicles", sound: "soft piano loop", src: "X viral threads" },
    { angle: "screen-recording tutorials with captions", sound: "lo-fi keys", src: "YT Shorts trending" },
    { angle: "controversial one-liner + comment bait", sound: "none (text-first)", src: "X engagement meta" },
    { angle: "day-in-the-grind b-roll montage", sound: "gym phonk", src: "IG Reels explore" },
    { angle: "'the algorithm hid this' curiosity gap", sound: "suspense pad", src: "Reddit r/socialmedia" },
    { angle: "receipts/screenshot proof posts", sound: "cash register FX", src: "X money niche" },
    { angle: "unpopular opinion stitches", sound: "original audio", src: "TikTok stitch meta" }
  ];

  /* ------------------------------------------------------------------ *
   * CTA integration (Step 3) — one CTA per post, driven by offer source
   * ------------------------------------------------------------------ */
  function buildCTA(shell, r) {
    const st = S().state;
    switch (shell.offerSource) {
      case "Promote Product Ghosts": {
        const p = st.products.find(x => x.id === shell.offerTargetProductId) ||
                  st.products.filter(x => x.status === "hit")[0] || st.products[0];
        if (p) return { text: `Get "${p.name}" — link in bio.`, style: "ghost-product", productId: p.id };
        return { text: "Product drop loading — follow so you don't miss it.", style: "ghost-product", productId: null };
      }
      case "Promote Affiliate Links":
        return { text: pick(r, ["The tool I use daily is in the bio (aff).", "Grab it through my link — costs you nothing extra.", "Top pick ranked in bio (affiliate)."]), style: "affiliate" };
      case "Collect Emails for List":
        return { text: pick(r, ["Download the free guide — link in bio.", "Free swipe file for subscribers — bio.", "Join 1,000+ getting the Sunday brief."]), style: "email" };
      case "Drive Traffic to Lead Gen Clone": {
        const clone = st.clones.find(c => c.id === shell.leadGenCloneId) || st.clones[0];
        const kw = (shell.niche.split(" ")[0] || "START").toUpperCase();
        return { text: `DM "${kw}" and my team answers within the hour.`, style: "lead-gen", cloneId: clone ? clone.id : null };
      }
      default:
        return { text: "Subscribe for more.", style: "generic" };
    }
  }

  /* ------------------------------------------------------------------ *
   * Post generation (Step 2) — real content, per platform format
   * ------------------------------------------------------------------ */
  function makePost(shell, platform, dayKey, r) {
    const persona = PERSONAS[shell.persona] || PERSONAS["Calm Genius"];
    const meta = nicheMeta(shell.niche);
    const topic = pick(r, meta.topics);
    const trend = pick(r, TRENDS);
    const hook = pick(r, persona.hooks);
    const cta = buildCTA(shell, r);
    const mimic = shell.referenceContent ? `\n[style ref honored: "${shell.referenceContent.slice(0, 60)}…"]` : "";

    let format, body, broll = null;
    if (platform === "X") {
      format = r() < 0.5 ? "tweet" : "thread";
      body = format === "tweet"
        ? `${hook} ${topic} — most get this backwards.\n\n${pick(r, persona.signoffs)}\n\n${cta.text}`
        : [`1/ ${hook} ${topic}. A 60-second breakdown.`,
           `2/ The mistake: chasing volume before nailing the angle (${trend.angle}).`,
           `3/ The fix: one niche, one promise, one proof per post.`,
           `4/ ${pick(r, persona.signoffs)}`,
           `5/ ${cta.text}`].join("\n\n");
    } else if (platform === "TikTok" || platform === "YT Shorts") {
      format = "short-script";
      body = [
        `HOOK (0-3s): "${hook} ${topic}."`,
        `BEAT 1 (3-10s): name the pain — who this is for and why today.`,
        `BEAT 2 (10-22s): the one move that changes it (trend angle: ${trend.angle}).`,
        `BEAT 3 (22-28s): proof line or before/after.`,
        `CTA (28-33s): "${cta.text}"`,
        ``,
        `SOUND: ${trend.sound} (${trend.src})`
      ].join("\n");
      broll = ["typing close-up / screen recording", "slow push-in on quote card", "b-roll: city night / gym iron / chart scroll (niche-matched)", "caption overlays every 2s"];
    } else { /* IG Reels */
      format = r() < 0.5 ? "carousel" : "meme-card";
      body = format === "carousel"
        ? [`SLIDE 1: ${hook} ${topic}`,
           `SLIDE 2: the 3 mistakes everyone makes`,
           `SLIDE 3: the fix (framework in one line)`,
           `SLIDE 4: proof / receipt`,
           `SLIDE 5: ${cta.text}`].join("\n")
        : `MEME CARD — visual: faceless silhouette + bold caption.\nTOP TEXT: ${hook}\nBOTTOM TEXT: ${topic} — ${pick(r, persona.signoffs)}\nCAPTION: ${cta.text}`;
    }

    return {
      id: S().uid("sp"),
      shellId: shell.id,
      day: dayKey,
      platform, format, hook, topic,
      trend: `${trend.angle} · ${trend.src}`,
      body: body + mimic,
      broll,
      cta: cta.text, ctaStyle: cta.style, ctaProductId: cta.productId || null, ctaCloneId: cta.cloneId || null,
      metrics: null
    };
  }

  /* ------------------------------------------------------------------ *
   * Engagement simulation (Step 4 input)
   * ------------------------------------------------------------------ */
  function personaFit(shell) {
    const p = PERSONAS[shell.persona];
    return (p && p.fit[shell.niche]) || 0.7;
  }

  function powerMeter(shell) { /* Faceless Power Meter: niche heat × persona fit × quality */
    const score = Math.round((nicheMeta(shell.niche).heat * 0.45 + personaFit(shell) * 0.35 + shell.quality * 0.25) * 100);
    return Math.max(5, Math.min(100, score));
  }

  function simulatePost(shell, post, dayIdx) {
    const r = E().rng(E().hashStr(post.id + ":" + dayIdx));
    const reach = 40 + shell.followers * (0.25 + r() * 0.5);
    const viral = r() < 0.04 ? 6 + r() * 10 : 1;                 /* 4% chance of a breakout */
    const views = Math.round(reach * nicheMeta(shell.niche).heat * personaFit(shell) * shell.quality * viral * (0.6 + r() * 0.9));
    const likes = Math.round(views * (0.03 + r() * 0.05));
    const follows = Math.round(views * (0.004 + r() * 0.009));
    const clicks = Math.round(views * (0.006 + r() * 0.012));
    post.metrics = { views, likes, follows, clicks, viral: viral > 1 };
    return post.metrics;
  }

  function attributeIncome(shell, post, clicks, r) {
    const st = S().state;
    if (post.ctaStyle === "ghost-product" && post.ctaProductId) {
      const p = st.products.find(x => x.id === post.ctaProductId);
      const unit = p && p.price > 0 ? p.price : 14;
      const sales = Math.round(clicks * (0.02 + r() * 0.04));
      return { income: sales * unit, note: sales ? `${sales} assisted sale(s) of "${p ? p.name : "product"}"` : null };
    }
    if (post.ctaStyle === "affiliate") {
      const income = Math.round(clicks * (0.5 + r() * 1.1));
      return { income, note: null };
    }
    if (post.ctaStyle === "email") {
      const emails = Math.round(clicks * (0.25 + r() * 0.3));
      shell.emailList = (shell.emailList || 0) + emails;
      return { income: 0, note: emails ? `+${emails} emails collected` : null };
    }
    if (post.ctaStyle === "lead-gen" && post.ctaCloneId) {
      const clone = st.clones.find(c => c.id === post.ctaCloneId);
      const leads = Math.round(clicks * (0.15 + r() * 0.2));
      if (clone && leads) {
        clone.stats.leads += leads;
        clone.memory.push(`+${leads} leads routed in by Outer Shell ${shell.name}.`);
        return { income: 0, note: `+${leads} leads routed to clone ${clone.name}` };
      }
      return { income: 0, note: null };
    }
    return { income: 0, note: null };
  }

  /* ------------------------------------------------------------------ *
   * Shell lifecycle
   * ------------------------------------------------------------------ */
  function createShell(input) {
    const st = S().state;
    const r = E().rng(E().hashStr("shell:" + (input.name || "") + Date.now()));
    const shell = {
      id: S().uid("sh"),
      name: (input.name || "SHELL").toUpperCase(),
      platforms: input.platforms && input.platforms.length ? input.platforms.slice() : ["X"],
      niche: input.niche || "AI Tools / Tech",
      persona: input.persona || "Calm Genius",
      offerSource: input.offerSource || OFFER_SOURCES[0],
      offerTargetProductId: input.offerTargetProductId || null,
      leadGenCloneId: input.leadGenCloneId || null,
      provider: input.provider || "auto",
      referenceContent: (input.referenceContent || "").trim().slice(0, 500),
      postsPerDay: Math.min(5, Math.max(1, input.postsPerDay || 2)),
      autoUpload: !!input.autoUpload,
      quality: input.quality != null ? Math.min(1.4, input.quality) : (0.55 + r() * 0.6),
      followers: input.followers != null ? input.followers : Math.round(40 + r() * 120),
      emailList: 0,
      daily: [],           /* {day, followers, views, likes, clicks, income} */
      posts: [],           /* capped archive */
      ctaStats: {},        /* style -> {posts, clicks} */
      personaTest: null,   /* {tryPersona, prevPersona, until, baseline} */
      memory: [],
      createdAt: now(),
      lastRunAt: null,
      lastEvolveAt: now(),
      generation: input.generation || 1,
      parentId: input.parentId || null
    };
    shell.memory.push(`Shell deployed — ${shell.niche} · ${shell.persona} · ${shell.platforms.join("/")} · mission: ${shell.offerSource}.`);
    if (st.dna && st.dna.decision) shell.memory.push(`Decision Framework inherited from GOD CORE (brain v${st.godBrainVersion}).`);
    if (shell.referenceContent) shell.memory.push(`Mimicry reference loaded (${shell.referenceContent.length} chars).`);
    st.shells.push(shell);
    S().logMemory("shell", `🎭 Outer Shell "${shell.name}" deployed — faceless ${shell.niche} brand on ${shell.platforms.join(", ")}.`);
    S().save();
    return shell;
  }

  /* Run one sim day for one shell. Returns digest events. */
  function runDay(shell, dayKey, dayIdx, queueAllowed) {
    const r = E().rng(E().hashStr(shell.id + ":" + dayKey));
    const events = [];
    const perDay = Math.min(5, shell.postsPerDay);
    const day = { day: dayKey, followers: shell.followers, views: 0, likes: 0, clicks: 0, income: 0 };

    for (let i = 0; i < perDay; i++) {
      const platform = shell.platforms[i % shell.platforms.length];
      const post = makePost(shell, platform, dayKey, r);
      const m = simulatePost(shell, post, dayIdx);
      const att = attributeIncome(shell, post, m.clicks, r);
      day.views += m.views; day.likes += m.likes; day.clicks += m.clicks; day.income += att.income;
      shell.followers += m.follows;
      const cs = shell.ctaStats[post.ctaStyle] = shell.ctaStats[post.ctaStyle] || { posts: 0, clicks: 0 };
      cs.posts += 1; cs.clicks += m.clicks;
      if (att.note) shell.memory.push(att.note + ` (${dayKey})`);
      if (m.viral) {
        events.push(`🔥 ${shell.name}: a ${platform} ${post.format} went viral — ${m.views.toLocaleString()} views, +${m.follows} followers.`);
        shell.memory.push(`Viral ${platform} ${post.format}: "${post.hook} ${post.topic}" — ${m.views.toLocaleString()} views.`);
      }
      shell.posts.push(post);
    }
    while (shell.posts.length > MAX_POSTS_ARCHIVE) shell.posts.shift();
    day.followers = shell.followers;
    shell.daily.push(day);
    if (shell.daily.length > 30) shell.daily.shift();
    shell.lastRunAt = now();

    /* Auto-Upload: queue today's best X post for real posting (X only —
       TikTok/IG/Shorts wait on future API integrations) */
    if (shell.autoUpload && queueAllowed) {
      const xPost = shell.posts.slice(-perDay).find(p => p.platform === "X");
      if (xPost) {
        const t = new Date(); t.setHours(t.getHours() + 1, 0, 0, 0);
        S().addQueueItem({
          cloneId: null,
          title: `🎭 ${shell.name} — daily drop`,
          text: (xPost.body.split("\n\n")[0] || xPost.body).slice(0, 270),
          dueAt: t.getTime()
        });
      }
    }
    return events;
  }

  function weeklyGrowthPct(shell) {
    if (shell.daily.length < 8) return null;
    const nowF = shell.followers;
    const weekAgo = shell.daily[shell.daily.length - 8].followers;
    if (!weekAgo) return null;
    return ((nowF - weekAgo) / weekAgo) * 100;
  }
  function dailyGrowthPct(shell) {
    if (shell.daily.length < 2) return 0;
    const prev = shell.daily[shell.daily.length - 2].followers || 1;
    return ((shell.followers - prev) / prev) * 100;
  }

  /* Step 4: evolve on engagement */
  function evolve(shell) {
    const events = [];
    const growth = weeklyGrowthPct(shell);
    if (growth == null) return events;

    /* resolve a running persona test */
    if (shell.personaTest && now() >= shell.personaTest.until) {
      const t = shell.personaTest;
      if (growth > (t.baseline == null ? 0 : t.baseline) + 1) {
        events.push(`🎭 ${shell.name}: persona test won — adopting ${shell.persona} permanently (${growth.toFixed(1)}%/wk vs ${t.baseline == null ? "?" : t.baseline.toFixed(1)}%).`);
        shell.memory.push(`Persona test adopted: ${shell.persona}.`);
      } else {
        shell.persona = t.prevPersona;
        events.push(`🎭 ${shell.name}: persona test failed — reverting to ${t.prevPersona}.`);
        shell.memory.push(`Persona test reverted to ${t.prevPersona}.`);
      }
      shell.personaTest = null;
      shell.lastEvolveAt = now();
      return events;
    }
    if (shell.personaTest) return events; /* test still running */

    if (now() - shell.lastEvolveAt < 7 * DAY) return events;
    shell.lastEvolveAt = now();

    if (growth > 10) {
      if (shell.postsPerDay < 5) {
        shell.postsPerDay += 1;
        events.push(`📈 ${shell.name} growing ${growth.toFixed(1)}%/week — scaling to ${shell.postsPerDay} posts/day.`);
        shell.memory.push(`Growth ${growth.toFixed(1)}%/wk → volume scaled to ${shell.postsPerDay}/day.`);
      }
    } else if (growth < 2) {
      const options = Object.keys(PERSONAS).filter(p => p !== shell.persona);
      const r = E().rng(E().hashStr(shell.id + ":swap:" + now()));
      const tryP = pick(r, options);
      shell.personaTest = { tryPersona: tryP, prevPersona: shell.persona, until: now() + 7 * DAY, baseline: growth };
      shell.persona = tryP;
      events.push(`⚠ ${shell.name} stagnant (${growth.toFixed(1)}%/wk) — auto-swapping persona to ${tryP} for a 7-day test.`);
      shell.memory.push(`Stagnation detected → 7-day persona test: ${tryP}.`);
    }
    return events;
  }

  /* Catch up all shells to the current sim day. */
  function process() {
    const st = S().state;
    const events = [];
    for (const shell of st.shells) {
      const start = shell.lastRunAt == null ? now() : shell.lastRunAt + DAY;
      let dayCount = shell.lastRunAt == null ? 1 : Math.floor((now() - shell.lastRunAt) / DAY);
      dayCount = Math.min(dayCount, 10); /* cap catch-up */
      let queued = false;
      for (let i = 0; i < dayCount; i++) {
        const dayKey = E().dateKey(new Date(start + i * DAY));
        const evs = runDay(shell, dayKey, shell.daily.length, !queued);
        if (shell.autoUpload) queued = true;
        events.push(...evs);
      }
      if (dayCount > 0) events.push(...evolve(shell));
    }
    if (st.shells.length) S().save();
    return events;
  }

  /* ------------------------------------------------------------------ *
   * Control-center commands
   * ------------------------------------------------------------------ */
  function cloneShell(id) {
    const st = S().state;
    const src = st.shells.find(s => s.id === id);
    if (!src) return null;
    const base = src.name.replace(/\s+(II|III|IV|V|VI|VII|VIII|IX|X)$/i, "");
    const gen = (src.generation || 1) + 1;
    const roman = ["", "", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"][Math.min(gen, 10)] || gen;
    const copy = createShell({
      name: `${base} ${roman}`,
      platforms: src.platforms, niche: src.niche, persona: src.persona,
      offerSource: src.offerSource, offerTargetProductId: src.offerTargetProductId,
      leadGenCloneId: src.leadGenCloneId, referenceContent: src.referenceContent,
      postsPerDay: src.postsPerDay, autoUpload: false,
      quality: Math.min(1.4, src.quality * 1.05),
      generation: gen, parentId: src.id
    });
    const best = bestHooks(src, 3);
    best.forEach(p => copy.memory.push(`Winning flow inherited: "${p.hook} ${p.topic}" (${p.metrics.views.toLocaleString()} views).`));
    S().logMemory("shell", `🎭 Shell "${src.name}" cloned → "${copy.name}" with its winning flows.`);
    S().save();
    return copy;
  }

  function crossPollinate(fromId, toId) {
    const st = S().state;
    const from = st.shells.find(s => s.id === fromId), to = st.shells.find(s => s.id === toId);
    if (!from || !to || from === to) return false;
    const bestStyle = Object.entries(from.ctaStats).sort((a, b) => b[1].clicks - a[1].clicks)[0];
    const hooks = bestHooks(from, 2);
    to.memory.push(`Cross-pollinated from ${from.name}: CTA style "${bestStyle ? bestStyle[0] : "generic"}"${hooks.length ? ` + hooks: ${hooks.map(h => `"${h.hook}"`).join(", ")}` : ""}.`);
    to.quality = Math.min(1.4, to.quality + 0.06);
    S().logMemory("shell", `🎭 CTA style copied from ${from.name} → ${to.name}.`);
    S().save();
    return true;
  }

  function bestHooks(shell, n) {
    return shell.posts.filter(p => p.metrics).sort((a, b) => b.metrics.views - a.metrics.views).slice(0, n || 5);
  }

  function stats() {
    const st = S().state;
    const followers = st.shells.reduce((a, s) => a + s.followers, 0);
    const income = st.shells.reduce((a, s) => a + s.daily.reduce((x, d) => x + d.income, 0), 0);
    const posts = st.shells.reduce((a, s) => a + s.daily.reduce((x, d) => x + 0, 0) + s.posts.length, 0);
    const emails = st.shells.reduce((a, s) => a + (s.emailList || 0), 0);
    return { shells: st.shells.length, followers, income, emails };
  }

  /* aggregate follower history for the weekly growth chart */
  function followerSeries() {
    const st = S().state;
    const labels = [], values = [];
    for (let i = 6; i >= 0; i--) {
      const key = E().dateKey(new Date(now() - i * DAY));
      let sum = 0;
      st.shells.forEach(s => {
        const rec = s.daily.filter(d => d.day <= key).slice(-1)[0];
        sum += rec ? rec.followers : 0;
      });
      labels.push("D-" + i);
      values.push(sum);
    }
    return { labels, values };
  }

  /* ------------------------------------------------------------------ *
   * Shell Builder AI — prompt → full faceless-brand launch plan
   * ------------------------------------------------------------------ */
  function detectNiche(text) {
    const t = text.toLowerCase();
    if (/fitness|gym|train/.test(t)) return "Fitness Motivation";
    if (/money|income|hustle|salar/.test(t)) return "Money Hacks";
    if (/crypto|coin|defi|trad/.test(t)) return "Crypto Signals";
    if (/mindset|discipline|perform/.test(t)) return "High-Performance Mindset";
    if (/copy|marketing|brand/.test(t)) return "Faceless Copywriting / Marketing Tips";
    return "AI Tools / Tech";
  }

  function builderLocal(promptText) {
    const niche = detectNiche(promptText);
    const r = E().rng(E().hashStr("builder:" + promptText));
    const meta = nicheMeta(niche);
    const word = niche.split(/[\s/]+/)[0].toLowerCase();
    const names = [
      `${word}.daily`, `the${word}vault`, `${word}protocol`, `silent${word}`, `${word}oracle_`
    ].map(n => n.replace(/[^a-z0-9._]/g, ""));
    const persona = pick(r, Object.keys(PERSONAS));
    const sellMatch = promptText.match(/sells?\s+(?:my\s+)?([^.,]+)/i);
    const offer = sellMatch ? sellMatch[1].trim() : "your lead product";
    const plan = [];
    for (let d = 1; d <= 10; d++) {
      plan.push(`Day ${d}: ${pick(r, meta.topics)} — ${pick(r, TRENDS).angle}${d % 3 === 0 ? " + soft CTA" : ""}${d === 10 ? " + hard launch post for " + offer : ""}`);
    }
    return [
      `=== ACCOUNT NAME IDEAS ===`, names.map(n => "@" + n).join("  ·  "),
      ``, `=== BIO ===`,
      `Faceless ${niche} intel · daily ${pick(r, ["systems", "signals", "playbooks"])} · no fluff, no face · ${offer} ↓`,
      ``, `=== 10-DAY CONTENT PLAN ===`, plan.join("\n"),
      ``, `=== POST SCHEDULE ===`,
      `2 posts/day: 09:00 (value post) + 19:00 (engagement post). Best-performer gets a re-cut across the other platforms within 24h.`,
      ``, `=== AFFILIATE / OFFER STRATEGY ===`,
      `Days 1-6 pure value (zero links) → day 7 soft mention → day 10 launch ${offer}. After 1k followers: 80/20 value-to-offer ratio, one pinned converter post.`,
      ``, `=== 3 HOOK STYLE VARIATIONS ===`,
      `A (${persona}): "${pick(r, PERSONAS[persona].hooks)}"`,
      `B (Savage Meme Lord): "${pick(r, PERSONAS["Savage Meme Lord"].hooks)}"`,
      `C (Mysterious Oracle): "${pick(r, PERSONAS["Mysterious Oracle"].hooks)}"`
    ].join("\n");
  }

  async function builderAI(promptText) {
    const st = S().state;
    const niche = detectNiche(promptText);
    /* Phase H0: provider resolution runs through the Provider Manager */
    const P = window.PRISM && PRISM.providers ? PRISM.providers : null;
    const sel = P ? P.resolve("auto", "Reasoning / strategy")
      : { id: (st.settings.engine === "neural" && st.settings.apiKey) ? "claude" : "local", switched: false };
    if (sel.id === "claude") {
      try {
        const dna = st.dna || {};
        const sys = [
          `You are Shell AI inside PRISM-X — you design faceless AI content brands ("Outer Shells").`,
          dna.decision ? `Decision Framework (non-negotiable):\n${dna.decision}` : "",
          `Output plain text with exactly these section headers: === ACCOUNT NAME IDEAS ===, === BIO ===, === 10-DAY CONTENT PLAN ===, === POST SCHEDULE ===, === AFFILIATE / OFFER STRATEGY ===, === 3 HOOK STYLE VARIATIONS ===.`
        ].filter(Boolean).join("\n");
        const text = await E().complete(sys, `Mission: ${promptText}\nDesign the complete faceless brand launch plan now.`, st.settings,
          { workerName: "Shell Builder AI", provider: "auto", category: "Reasoning / strategy" });
        if (/=== ACCOUNT NAME IDEAS ===/.test(text)) return { text, engine: "neural", niche };
      } catch (e) { /* fall through */ }
    }
    const text = builderLocal(promptText);
    if (P) P.recordLocal({ workerName: "Shell Builder AI", requested: sel.requested, switched: sel.switched, reason: sel.reason, chars: text.length });
    return { text, engine: "local", niche };
  }

  function deleteShell(id) {
    const st = S().state;
    const s = st.shells.find(x => x.id === id);
    st.shells = st.shells.filter(x => x.id !== id);
    if (s) S().logMemory("shell", `🎭 Shell "${s.name}" dissolved.`);
    S().save();
  }

  return {
    PLATFORMS, NICHES, PERSONAS, OFFER_SOURCES,
    now, createShell, process, evolve, cloneShell, crossPollinate, deleteShell,
    bestHooks, stats, followerSeries, powerMeter, personaFit,
    weeklyGrowthPct, dailyGrowthPct, builderAI, money
  };
})();
