import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ExecutionLog, Mission, MissionReview, ReviewOutcome, Task } from '@prisma/client';
import {
  LearningEntryRepository,
  MissionReviewRepository,
} from '../database/repositories/learning.repositories';
import {
  MissionRepository,
  TaskRepository,
} from '../database/repositories/tenant.repositories';
import { AuditLogRepository } from '../database/repositories/tenant.repositories';
import { ExecutionLogRepository } from '../database/repositories/execution.repositories';
import { EventBusService } from '../events/event-bus.service';
import { DomainEvent } from '../events/domain-events';
import { RequestContextStore } from '../shared/context/request-context';
import * as Confidence from './confidence';

export interface Bottleneck {
  taskId: string;
  title: string;
  durationMs: number;
  /** Fraction of the mission's total task time this one task consumed. */
  share: number;
}

export interface MissedOpportunity {
  kind: string;
  detail: string;
  /** What it would plausibly have saved, where that can be estimated. */
  estimate?: string;
}

/**
 * Turns a finished mission into a lesson.
 *
 * The review is written from the mission's own record — tasks, execution
 * logs, audit trail — and not from a model's opinion of how it went. That is
 * deliberate: a post-mortem generated by asking an LLM "how did that go?"
 * produces fluent prose whose relationship to what happened is unverifiable,
 * and every downstream analysis would inherit that. Everything here is
 * arithmetic over rows, so a number in a review can be traced to the events
 * that produced it.
 *
 * One review per mission, permanently. It outlives the mission's tasks and
 * is the unit the rest of the Learning Engine reasons over.
 */
@Injectable()
export class MissionReviewService implements OnModuleInit {
  private readonly logger = new Logger(MissionReviewService.name);

  /** A task taking more than this share of total task time is a bottleneck. */
  static readonly BOTTLENECK_SHARE = 0.35;
  /** Overrun beyond the estimate, as a multiple, before it is worth noting. */
  static readonly OVERRUN_FACTOR = 1.5;

  constructor(
    private readonly reviews: MissionReviewRepository,
    private readonly missions: MissionRepository,
    private readonly tasks: TaskRepository,
    private readonly executionLogs: ExecutionLogRepository,
    private readonly auditLogs: AuditLogRepository,
    private readonly learning: LearningEntryRepository,
    private readonly events: EventBusService,
  ) {}

  onModuleInit(): void {
    // A mission ending is what makes a review possible, so the review is
    // driven by the event rather than by anyone remembering to ask for one.
    for (const name of [
      DomainEvent.MissionCompleted,
      DomainEvent.MissionFailed,
    ]) {
      this.events.on(name, async (event) => {
        const missionId = (event.payload as { missionId?: string }).missionId;
        if (!missionId) return;
        try {
          await this.asOrganization(event.organizationId, () => this.review(missionId));
        } catch (error) {
          // A failed review must not fail the mission that triggered it —
          // the mission is already over, and losing its post-mortem is a
          // smaller harm than an exception propagating into the orchestrator.
          this.logger.warn(
            `Could not review mission ${missionId}: ${(error as Error).message}`,
          );
        }
      });
    }
  }

  /**
   * Builds (or rebuilds) the review for one mission.
   *
   * Idempotent: reviewing twice overwrites rather than duplicating, so a
   * replayed event or a manual re-run converges instead of accumulating.
   */
  async review(missionId: string): Promise<MissionReview> {
    const mission = await this.missions.findByIdOrFail(missionId);
    const [tasks, logs, humanActions] = await Promise.all([
      this.tasks.findByMission(missionId),
      this.executionLogs.findByMission(missionId, 500),
      // What a person actually did to this mission. Audit rows are the only
      // record of human involvement that spans every way of intervening —
      // retrying it, cancelling it, editing a task — rather than one of them.
      this.auditLogs.findMany(
        { resource: 'mission', resourceId: missionId, userId: { not: null } },
        { take: 200, orderBy: { createdAt: 'asc' } },
      ),
    ]);

    const facts = MissionReviewService.analyse(mission, tasks, logs);
    const humanInterventions = humanActions.length;

    // Confidence in a single review is about how much *evidence the mission
    // itself* provides. A one-task mission tells you very little about
    // anything, including itself.
    const confidence = Confidence.score({
      samples: tasks.length + logs.length,
      consistency: facts.consistency,
    });

    const payload = {
      missionId,
      objective: mission.objective,
      outcome: facts.outcome,
      successScore: facts.successScore,
      completionMs: facts.completionMs,
      estimatedMs: facts.estimatedMs,
      costUsd: facts.costUsd,
      estimatedCostUsd: facts.estimatedCostUsd,
      totalTokens: facts.totalTokens,
      taskCount: tasks.length,
      tasksSucceeded: facts.tasksSucceeded,
      tasksFailed: facts.tasksFailed,
      retryCount: facts.retryCount,
      humanInterventions,
      humanMinutes: MissionReviewService.estimateHumanMinutes(humanActions),
      errors: facts.errors,
      bottlenecks: facts.bottlenecks as never,
      missedOpportunities: facts.missedOpportunities as never,
      recommendations: facts.recommendations as never,
      summary: MissionReviewService.summarise(mission, facts, humanInterventions),
      tags: MissionReviewService.tagsFor(mission, facts),
      confidence: confidence.value,
      sampleSize: tasks.length + logs.length,
    };

    const existing = await this.reviews.findForMission(missionId);
    const review = existing
      ? await this.reviews.update(existing.id, payload)
      : await this.reviews.create(payload);

    await this.recordLesson(review);

    await this.events.publish(DomainEvent.MissionReviewed, {
      missionId,
      reviewId: review.id,
      outcome: review.outcome,
      successScore: review.successScore,
      confidence: review.confidence,
    });

    return review;
  }

  async get(missionId: string): Promise<MissionReview | null> {
    return this.reviews.findForMission(missionId);
  }

  async list(take = 50): Promise<MissionReview[]> {
    return this.reviews.recent(take);
  }

  async search(query: string, take = 25): Promise<MissionReview[]> {
    return this.reviews.search(query, take);
  }

  // ----------------------------------------------------------------
  // Analysis — pure, so it can be tested without a database
  // ----------------------------------------------------------------

  static analyse(
    mission: Pick<
      Mission,
      'status' | 'startedAt' | 'completedAt' | 'createdAt' | 'plan' | 'objective'
    >,
    tasks: Task[],
    logs: ExecutionLog[],
  ) {
    const tasksSucceeded = tasks.filter((t) => t.status === 'COMPLETED').length;
    const tasksFailed = tasks.filter((t) => t.status === 'FAILED').length;
    const retryCount = tasks.reduce((sum, t) => sum + Math.max(0, t.attempts - 1), 0);

    const startedAt = mission.startedAt ?? mission.createdAt;
    const completedAt = mission.completedAt ?? new Date();
    const completionMs = Math.max(0, completedAt.getTime() - startedAt.getTime());

    const costUsd = Number(
      logs.reduce((sum, log) => sum + log.costUsd, 0).toFixed(6),
    );
    const totalTokens = logs.reduce((sum, log) => sum + log.totalTokens, 0);

    const estimatedSeconds = tasks.reduce((sum, t) => sum + (t.estimatedSeconds ?? 0), 0);
    const estimatedCost = tasks.reduce((sum, t) => sum + (t.estimatedCostUsd ?? 0), 0);

    const durations = tasks
      .filter((t) => t.startedAt && t.completedAt)
      .map((t) => ({
        task: t,
        durationMs: t.completedAt!.getTime() - t.startedAt!.getTime(),
      }));
    const totalTaskMs = durations.reduce((sum, d) => sum + d.durationMs, 0);

    const bottlenecks: Bottleneck[] = durations
      .map((d) => ({
        taskId: d.task.id,
        title: d.task.title,
        durationMs: d.durationMs,
        share: totalTaskMs > 0 ? Number((d.durationMs / totalTaskMs).toFixed(4)) : 0,
      }))
      // A single task in a one-task mission is 100% of the time and is not
      // a bottleneck — it is the whole mission. Needs at least two.
      .filter((b) => durations.length > 1 && b.share >= MissionReviewService.BOTTLENECK_SHARE)
      .sort((a, b) => b.share - a.share)
      .slice(0, 5);

    const errors = [
      ...new Set(
        [
          ...tasks.map((t) => t.error).filter((e): e is string => Boolean(e)),
          ...logs.map((l) => l.error).filter((e): e is string => Boolean(e)),
        ].map((e) => MissionReviewService.errorSignature(e)),
      ),
    ].slice(0, 20);

    const outcome = MissionReviewService.outcomeFor(mission.status, tasksSucceeded, tasksFailed);
    const successScore = MissionReviewService.scoreSuccess({
      tasks: tasks.length,
      succeeded: tasksSucceeded,
      failed: tasksFailed,
      retries: retryCount,
      overBudget: estimatedCost > 0 && costUsd > estimatedCost * MissionReviewService.OVERRUN_FACTOR,
      outcome,
    });

    // How steadily the mission ran. A mission whose tasks all took roughly
    // the same time is better understood than one that ranged from 2s to 400s.
    const consistency = Confidence.consistencyOf(durations.map((d) => d.durationMs));

    const missedOpportunities = MissionReviewService.findMissedOpportunities({
      tasks,
      logs,
      bottlenecks,
      estimatedSeconds,
      completionMs,
      estimatedCost,
      costUsd,
    });

    return {
      outcome,
      successScore,
      completionMs,
      estimatedMs: estimatedSeconds > 0 ? estimatedSeconds * 1000 : null,
      costUsd,
      estimatedCostUsd: estimatedCost > 0 ? Number(estimatedCost.toFixed(6)) : null,
      totalTokens,
      tasksSucceeded,
      tasksFailed,
      retryCount,
      errors,
      bottlenecks,
      missedOpportunities,
      consistency,
      recommendations: MissionReviewService.proposeImprovements({
        tasksFailed,
        retryCount,
        bottlenecks,
        errors,
        overBudget: estimatedCost > 0 && costUsd > estimatedCost * MissionReviewService.OVERRUN_FACTOR,
      }),
    };
  }

  static outcomeFor(status: string, succeeded: number, failed: number): ReviewOutcome {
    if (status === 'CANCELLED' || status === 'ARCHIVED') return ReviewOutcome.CANCELLED;
    if (status === 'FAILED') {
      // A failed mission that nonetheless completed most of its work is a
      // partial result, and calling it a flat failure would discard the
      // distinction that makes the review useful.
      return succeeded > failed && succeeded > 0 ? ReviewOutcome.PARTIAL : ReviewOutcome.FAILURE;
    }
    if (failed > 0) return ReviewOutcome.PARTIAL;
    return ReviewOutcome.SUCCESS;
  }

  /**
   * A 0..1 score built only from things the system actually recorded.
   *
   * Completion dominates, because a mission that did not do its work is not
   * rescued by having been cheap. Retries and budget overrun subtract, since
   * both mean the result cost more than it should have.
   */
  static scoreSuccess(input: {
    tasks: number;
    succeeded: number;
    failed: number;
    retries: number;
    overBudget: boolean;
    outcome: ReviewOutcome;
  }): number {
    if (input.outcome === ReviewOutcome.CANCELLED) return 0;
    if (input.tasks === 0) {
      return input.outcome === ReviewOutcome.SUCCESS ? 0.5 : 0;
    }

    const completion = input.succeeded / input.tasks;
    const retryPenalty = Math.min(0.2, (input.retries / input.tasks) * 0.2);
    const budgetPenalty = input.overBudget ? 0.1 : 0;

    const score = completion * 0.8 + (input.failed === 0 ? 0.2 : 0) - retryPenalty - budgetPenalty;
    return Number(Math.min(1, Math.max(0, score)).toFixed(4));
  }

  /**
   * What could have gone better, stated only where the record supports it.
   *
   * Every entry here has to be derivable from the rows — no speculative
   * advice, because a review full of plausible-sounding suggestions nobody
   * can check is worse than a short one.
   */
  static findMissedOpportunities(input: {
    tasks: Task[];
    logs: ExecutionLog[];
    bottlenecks: Bottleneck[];
    estimatedSeconds: number;
    completionMs: number;
    estimatedCost: number;
    costUsd: number;
  }): MissedOpportunity[] {
    const found: MissedOpportunity[] = [];

    // Tasks with no dependencies on each other ran one after another.
    const independent = input.tasks.filter((t) => t.dependsOn.length === 0);
    if (independent.length > 1) {
      const serial = independent
        .filter((t) => t.startedAt && t.completedAt)
        .sort((a, b) => a.startedAt!.getTime() - b.startedAt!.getTime());

      const overlapped = serial.some((task, i) =>
        i > 0 ? task.startedAt!.getTime() < serial[i - 1].completedAt!.getTime() : false,
      );

      if (serial.length > 1 && !overlapped) {
        const saved = serial
          .slice(1)
          .reduce((sum, t) => sum + (t.completedAt!.getTime() - t.startedAt!.getTime()), 0);
        found.push({
          kind: 'unused_parallelism',
          detail:
            `${serial.length} tasks had no dependencies on one another but ran in sequence.`,
          estimate: `up to ${Math.round(saved / 1000)}s of wall-clock time`,
        });
      }
    }

    if (input.estimatedSeconds > 0) {
      const overrun = input.completionMs / (input.estimatedSeconds * 1000);
      if (overrun > MissionReviewService.OVERRUN_FACTOR) {
        found.push({
          kind: 'estimate_drift',
          detail:
            `Took ${overrun.toFixed(1)}× the planned time — the planner's estimates ` +
            'for this kind of work are running short.',
        });
      }
    }

    if (input.estimatedCost > 0 && input.costUsd > input.estimatedCost * MissionReviewService.OVERRUN_FACTOR) {
      found.push({
        kind: 'budget_overrun',
        detail:
          `Cost $${input.costUsd.toFixed(4)} against an estimate of ` +
          `$${input.estimatedCost.toFixed(4)}.`,
      });
    }

    // Retries that eventually succeeded are latency and spend the mission
    // paid for nothing.
    const retried = input.tasks.filter((t) => t.attempts > 1 && t.status === 'COMPLETED');
    if (retried.length > 0) {
      found.push({
        kind: 'wasted_retries',
        detail:
          `${retried.length} task(s) succeeded only after retrying — the first attempt ` +
          'was paid for and discarded.',
      });
    }

    // Several models in one mission is not wrong, but it makes the mission
    // hard to attribute and is usually accidental.
    const models = new Set(input.logs.map((l) => l.model).filter(Boolean));
    if (models.size > 2) {
      found.push({
        kind: 'model_sprawl',
        detail: `Ran across ${models.size} different models: ${[...models].join(', ')}.`,
      });
    }

    return found.slice(0, 6);
  }

  static proposeImprovements(input: {
    tasksFailed: number;
    retryCount: number;
    bottlenecks: Bottleneck[];
    errors: string[];
    overBudget: boolean;
  }): Array<{ kind: string; detail: string }> {
    const proposals: Array<{ kind: string; detail: string }> = [];

    if (input.tasksFailed > 0) {
      proposals.push({
        kind: 'investigate_failures',
        detail:
          `${input.tasksFailed} task(s) failed. Recurring signatures: ` +
          `${input.errors.slice(0, 3).join('; ') || 'none recorded'}.`,
      });
    }

    for (const bottleneck of input.bottlenecks.slice(0, 2)) {
      proposals.push({
        kind: 'address_bottleneck',
        detail:
          `"${bottleneck.title}" took ${(bottleneck.share * 100).toFixed(0)}% of total ` +
          'task time. Split it, cache its input, or run it alongside its siblings.',
      });
    }

    if (input.retryCount > 2) {
      proposals.push({
        kind: 'reduce_retries',
        detail:
          `${input.retryCount} retries across the mission. Check provider health and ` +
          'whether the failing step needs a longer timeout rather than another attempt.',
      });
    }

    if (input.overBudget) {
      proposals.push({
        kind: 'cost_control',
        detail: 'Cost exceeded the plan. A cheaper model may serve the same steps.',
      });
    }

    return proposals;
  }

  /**
   * Collapses an error message to a comparable signature.
   *
   * Ids, timestamps and quantities differ between two occurrences of the
   * same fault; without stripping them, every failure looks unique and the
   * pattern engine downstream can never see that something has happened
   * eleven times.
   */
  static errorSignature(message: string): string {
    return message
      .replace(/\b[0-9a-f]{8,}\b/gi, '<id>')
      .replace(/\b\d{4}-\d{2}-\d{2}T[\d:.]+Z?\b/g, '<time>')
      .replace(/\b\d+(\.\d+)?\b/g, '<n>')
      .replace(/\s+/g, ' ')
      .trim()
      .slice(0, 200);
  }

  static summarise(
    mission: Pick<Mission, 'objective'>,
    facts: ReturnType<typeof MissionReviewService.analyse>,
    humanInterventions: number,
  ): string {
    const parts = [
      `${facts.outcome.toLowerCase()} (${(facts.successScore * 100).toFixed(0)}%)`,
      `${facts.tasksSucceeded}/${facts.tasksSucceeded + facts.tasksFailed} tasks`,
      `${Math.round(facts.completionMs / 1000)}s`,
      `$${facts.costUsd.toFixed(4)}`,
    ];
    if (humanInterventions > 0) parts.push(`${humanInterventions} human decision(s)`);
    if (facts.bottlenecks.length > 0) parts.push(`${facts.bottlenecks.length} bottleneck(s)`);
    if (facts.errors.length > 0) parts.push(`${facts.errors.length} distinct error(s)`);

    return `${mission.objective} — ${parts.join(', ')}.`;
  }

  static tagsFor(
    mission: Pick<Mission, 'objective'>,
    facts: ReturnType<typeof MissionReviewService.analyse>,
  ): string[] {
    const tags = new Set<string>([facts.outcome.toLowerCase()]);

    if (facts.tasksFailed > 0) tags.add('had-failures');
    if (facts.retryCount > 0) tags.add('retried');
    if (facts.bottlenecks.length > 0) tags.add('bottleneck');
    if (facts.successScore >= 0.9) tags.add('clean-run');
    for (const opportunity of facts.missedOpportunities) tags.add(opportunity.kind.replace(/_/g, '-'));

    // Objective keywords, so a review is findable by what it was about and
    // not only by how it went.
    for (const word of mission.objective.toLowerCase().split(/\W+/)) {
      if (word.length > 4 && tags.size < 12) tags.add(word);
    }

    return [...tags];
  }

  /**
   * Rough attention cost of the human actions taken on a mission.
   *
   * Gaps between consecutive actions are capped at five minutes each: a
   * person who retried a mission and then approved something the next
   * morning did not spend fourteen hours on it, and wall-clock elapsed time
   * would report exactly that. A lone action counts as one minute — it took
   * *some* attention, and pretending otherwise would make every
   * single-touch mission look fully automated.
   */
  static estimateHumanMinutes(actions: Array<{ createdAt: Date }>): number {
    if (actions.length === 0) return 0;
    if (actions.length === 1) return 1;

    const ordered = [...actions].sort(
      (a, b) => a.createdAt.getTime() - b.createdAt.getTime(),
    );

    const minutes = ordered.slice(1).reduce((sum, action, i) => {
      const gap = action.createdAt.getTime() - ordered[i].createdAt.getTime();
      return sum + Math.min(5, gap / 60_000);
    }, 1);

    return Number(minutes.toFixed(2));
  }

  // ----------------------------------------------------------------
  // Internals
  // ----------------------------------------------------------------

  /** Mirrors the review into the learning repository as a durable lesson. */
  private async recordLesson(review: MissionReview): Promise<void> {
    const existing = await this.learning.findBySource('mission_review', review.id);
    const payload = {
      kind: 'MISSION_REVIEW' as const,
      title: `Review: ${review.objective.slice(0, 120)}`,
      body: review.summary,
      sourceType: 'mission_review',
      sourceId: review.id,
      data: {
        outcome: review.outcome,
        successScore: review.successScore,
        costUsd: review.costUsd,
        completionMs: review.completionMs,
        bottlenecks: review.bottlenecks,
        missedOpportunities: review.missedOpportunities,
      } as never,
      tags: review.tags,
      confidence: review.confidence,
      sampleSize: review.sampleSize,
    };

    if (existing) await this.learning.update(existing.id, payload);
    else await this.learning.create(payload);
  }

  private asOrganization<T>(organizationId: string, fn: () => Promise<T>): Promise<T> {
    return RequestContextStore.run(
      {
        userId: 'system',
        organizationId,
        roleKey: 'SYSTEM',
        permissions: ['*'],
        requestId: `review-${Date.now()}`,
      },
      fn,
    );
  }
}
